global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'l4-support-service'
  static_configs:
  - targets: [ 'app:8080' ]
  metrics_path: /api/v1/metrics
  scrape_interval: 5s

- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]
